name: goreleaser edge containers

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  goreleaser:
    permissions:
      # Add "contents" to write release
      contents: 'write'
      # Add "id-token" for google-github-actions/auth
      id-token: 'write'

    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare tag version
        run: |
          RAW_VERSION=$(make version)
          echo "VERSION=${RAW_VERSION/\+/-}" >> $GITHUB_ENV
      - name: Locally tag the current commit
        run: git tag ${{ env.VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release -f .github/.goreleaser-edge.yml --rm-dist --timeout 120m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NFPM_DEFAULT_RPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Start mondoo-operator integration tests
        run: |
          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_API_TOKEN }}" \
            https://api.github.com/repos/mondoohq/mondoo-operator/actions/workflows/31262606/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"cnspecImageTag\":\"edge-${{ env.VERSION }}-rootless\"}}"
      
