name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  goreleaser:
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Git config
        run: git config --global url."https://${{ secrets.GH_API_TOKEN}}@github.com".insteadOf "https://github.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --timeout 120m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install RPM packaging dependencies
        run: sudo apt-get install -y rpm reprepro
      - name: Set up GPG for RPM
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" > passphrase
          echo "${{ secrets.GPG_PUBKEY }}" > mondoo_gpg2_pub.gpg
          echo "${{ secrets.GPG_PUBKEY }}" | gpg --import --no-tty --batch --yes
          echo "${{ secrets.GPG_SECKEY }}" | gpg --import --passphrase-file passphrase --allow-secret-key-import --pinentry-mode loopback --no-tty --batch --yes
          echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
          # Find keygrip with 'gpg --list-secret-keys --with-keygrip'
          gpg-connect-agent RELOADAGENT /bye
          echo "${{secrets.GPG_PASSPHRASE}}" | /usr/lib/gnupg2/gpg-preset-passphrase --preset "${{secrets.GPG_KEYGRIP}}"
          rpm --import mondoo_gpg2_pub.gpg
      - name: Sign RPMs
        run: |
          cp scripts/rpmmacros ~/.rpmmacros
          export GPG_TTY=$(tty)
          ls -l dist/*.rpm
          rpmsign --addsign dist/*.rpm
          # Check package data and signatures
          rpm -qpi dist/*.rpm

